
DROP TABLE IF EXISTS search;
CREATE VIRTUAL TABLE search USING fts5(PRODUCT_ID, DEVICE, PRODUCT, PRODUCT_CODE, MANUFACTURER, UDI);


INSERT
INTO
	search (PRODUCT_ID, DEVICE, PRODUCT, PRODUCT_CODE, MANUFACTURER, UDI)
SELECT
    P.PRODUCT_ID,
	d.DEVICE_TYPE_NAME, -- DEVICE
	P.BRAND_TRADE_NAME, -- PRODUCT
	P.PRODUCT_CODE,
	P.MANUFACTURER_NAME, -- MANUFACTURER
	P.UDI_NUMBER -- UDI
FROM
	products AS P
INNER JOIN devices AS D ON
    D.DEVICE_ID = P.DEVICE_ID;
