
DROP TABLE IF EXISTS search;
CREATE VIRTUAL TABLE search USING fts5(PRODUCT_ID, DEVICE, PRODUCT, PRODUCT_CODE, MANUFACTURER, UDI, GMDN);


INSERT
INTO
	search (PRODUCT_ID, DEVICE, PRODUCT, PRODUCT_CODE, MANUFACTURER, UDI, GMDN)
SELECT
    P.PRODUCT_ID,
	D.DEVICE_TYPE_NAME, -- DEVICE
	P.BRAND_TRADE_NAME, -- PRODUCT
	P.PRODUCT_CODE,
	P.MANUFACTURER_NAME, -- MANUFACTURER
	P.UDI_NUMBER,  -- UDI
	D.GMDN_TERM_NAME -- GMDN
FROM
	products AS P
INNER JOIN devices AS D ON
    D.DEVICE_ID = P.DEVICE_ID;
