INSERT INTO organisations (
    MAN_ORGANISATION_ID,
    MAN_CREATED_DATE,
    MAN_ORGANISATION_NAME,
    MAN_ADDR_LINE_1,
    MAN_ADDR_LINE_2,
    MAN_ADDR_LINE_3,
    MAN_ADDR_LINE_4,
    MAN_CITY,
    MAN_COUNTYSTATEPROVINCE,
    MAN_COUNTRY,
    REP_NAME,
    REP_ADDRESS_LINE_1,
    REP_ADDRESS_LINE_2,
    REP_ADDRESS_LINE_3,
    REP_ADDRESS_LINE_4,
    REP_CITY,
    REP_COUNTY_STATE_PROVINCE,
    REP_COUNTRY,
    RELATIONSHIP,
    LAST_UPDATED_DATE,
    MAN_ACCOUNT_NUMBER,
    MAN_POSTCODE,
    REP_POSTCODE,
    REP_ORGANISATION_ID
    --PARD_OPTIONS_ID,
    --PARTY_ID,
    --IS_PUBLISH_MANUFACTURER_NAME,
    --IS_PUBLISH_AUTHORISEDREP_NAME,
    --IS_PUBLISH_MANUFACTURER_ADDRESS,
    --IS_PUBLISH_AUTHORISEDREP_ADDRESS,
    --FROM_DATE,
    --TO_DATE,
    --IS_CURRENT,
    --CUSTOMER_SERVICE_EMAIL_ADDRESS,
    --CUSTOMER_SERVICE_TELEPHONE_NUMBER,
    --REP_CUSTOMER_SERVICE_EMAIL_ADDRESS,
    --REP_CUSTOMER_SERVICE_TELEPHONE_NUMBER
)
SELECT
    json_extract(value, '$.MAN_ORGANISATION_ID'),
    json_extract(value, '$.MAN_CREATED_DATE'),
    json_extract(value, '$.MAN_ORGANISATION_NAME'),
    json_extract(value, '$.MAN_ADDR_LINE_1'),
    json_extract(value, '$.MAN_ADDR_LINE_2'),
    json_extract(value, '$.MAN_ADDR_LINE_3'),
    json_extract(value, '$.MAN_ADDR_LINE_4'),
    json_extract(value, '$.MAN_CITY'),
    json_extract(value, '$.MAN_COUNTYSTATEPROVINCE'),
    json_extract(value, '$.MAN_COUNTRY'),
    json_extract(value, '$.REP_NAME'),
    json_extract(value, '$.REP_ADDRESS_LINE_1'),
    json_extract(value, '$.REP_ADDRESS_LINE_2'),
    json_extract(value, '$.REP_ADDRESS_LINE_3'),
    json_extract(value, '$.REP_ADDRESS_LINE_4'),
    json_extract(value, '$.REP_CITY'),
    json_extract(value, '$.REP_COUNTY_STATE_PROVINCE'),
    json_extract(value, '$.REP_COUNTRY'),
    json_extract(value, '$.RELATIONSHIP'),
    json_extract(value, '$.LAST_UPDATED_DATE'),
    json_extract(value, '$.MAN_ACCOUNT_NUMBER'),
    json_extract(value, '$.MAN_POSTCODE'),
    json_extract(value, '$.REP_POSTCODE'),
    json_extract(value, '$.REP_ORGANISATION_ID')
FROM
    json_each(readfile('manufacturers.json'));
