INSERT
INTO
	search (DEVICE_ID, PRODUCT, MANUFACTURER, UDI)
SELECT
	d.DEVICE_ID,
	d.DEVICE_TYPE_NAME,
	o.MAN_ORGANISATION_NAME,
	d.DEV_UDI_NUMBERS
FROM
	devices AS d
INNER JOIN organisations AS o ON
    d.MAN_ORGANISATION_ID = o.MAN_ORGANISATION_ID;
