CREATE INDEX DVC_DEVICE_PRODUCT_MAPPING__DEVICE ON DVC_DEVICE_PRODUCT_MAPPING(DEVICE_ID);
CREATE INDEX DVC_DEVICE_PRODUCT_MAPPING__PRODUCT ON DVC_DEVICE_PRODUCT_MAPPING(PRODUCT_ID);

CREATE UNIQUE INDEX DVC_DEVICE_PRODUCT__PRODUCT ON DVC_DEVICE_PRODUCT(PRODUCT_ID);
CREATE INDEX DVC_DEVICE_PRODUCT__MANUFACTURER ON DVC_DEVICE_PRODUCT(MANUFACTURER_ID);

CREATE UNIQUE INDEX DVC_DEVICE__DEVICE ON DVC_DEVICE(DEVICE_ID);
CREATE INDEX DVC_DEVICE__MANUFACTURER ON DVC_DEVICE(MANUFACTURER_ID);
CREATE INDEX DVC_DEVICE__RELATED_DEVICE ON DVC_DEVICE(RELATED_DEVICE_ID);

CREATE UNIQUE INDEX DVC_ORGANISATION__ORGANISATION ON DVC_ORGANISATION(ORGANISATION_ID);

CREATE UNIQUE INDEX DVC_REF_UDI_ENTITY__ENTITY ON DVC_REF_UDI_ENTITY(UDI_ENTITY_ID);

