name: Fly Deploy

on:
  push:
    branches:
      - main
    paths:
      - prototypes/v1/**

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # ensure only one action runs at a time
    defaults:
      run:
        working-directory: ./prototypes/v1/
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_V1 }}
